/** Shared tool name → friendly label mapping used across agent UI */

export const TOOL_LABELS: Record<string, { label: string }> = {
  creator_search: { label: "Searching creators" },
  get_creator_details: { label: "Loading creator profile" },
  lookalike_finder: { label: "Finding similar creators" },
  warm_lead_detector: { label: "Detecting warm leads" },
  competitor_mapper: { label: "Mapping competitor creators" },
  geo_opportunity_finder: { label: "Finding geo opportunities" },
  audience_overlap_check: { label: "Checking audience overlap" },
  outreach_drafter: { label: "Drafting outreach email" },
  propose_outreach: { label: "Submitting for approval" },
  rate_benchmarker: { label: "Benchmarking rates" },
  counter_offer_generator: { label: "Generating counter-offer" },
  deal_memo_generator: { label: "Creating deal memo" },
  budget_optimizer: { label: "Analyzing budget" },
  roi_calculator: { label: "Calculating ROI" },
  campaign_overview: { label: "Loading campaigns" },
  campaign_builder: { label: "Building campaign" },
  campaign_status_manager: { label: "Updating campaign status" },
  content_tracker: { label: "Tracking content" },
  brief_generator: { label: "Generating brief" },
  discount_code_generator: { label: "Creating discount codes" },
  gifting_order_creator: { label: "Creating gifting order" },
  relationship_scorer: { label: "Scoring relationship" },
  ambassador_identifier: { label: "Identifying ambassadors" },
  churn_predictor: { label: "Predicting churn risk" },
  reengagement_recommender: { label: "Finding re-engagement targets" },
};
